import { ReceiptModel } from "../types/ReceiptModel";
import { DocumentBuilder } from "./Document";

export interface GSTReportData {
  date: string;
  totalTaxableAmount: number;
  cgstAmount: number;
  sgstAmount: number;
  totalGst: number;
  totalGrossSales: number;
  billsCount: number;
}

export class GSTDocument implements DocumentBuilder {
  public build(data: GSTReportData, version = 1): ReceiptModel {
    const meta: Record<string, string> = {
      "Report Date": data.date,
      "Bills Count": data.billsCount.toString(),
      "Generated At": new Date().toLocaleTimeString("en-IN", { timeZone: "Asia/Kolkata" })
    };

    const summary = [
      { label: "Taxable Amount:", value: `₹${data.totalTaxableAmount.toFixed(2)}` },
      { label: "CGST (2.5%):", value: `₹${data.cgstAmount.toFixed(2)}` },
      { label: "SGST (2.5%):", value: `₹${data.sgstAmount.toFixed(2)}` },
      { label: "TOTAL GST (5%):", value: `₹${data.totalGst.toFixed(2)}`, isBold: true },
      { label: "GROSS SALES:", value: `₹${data.totalGrossSales.toFixed(2)}`, isBold: true }
    ];

    return {
      receiptVersion: version,
      type: "gst",
      currency: "INR",
      locale: "en-IN",
      timezone: "Asia/Kolkata",
      header: {
        restaurantName: "GST TAX COLLECTION",
        branchName: "Paakashala",
        address: "TAX REGISTRY SUMMARY",
        phone: ""
      },
      meta,
      items: [],
      summary,
      footer: {
        notes: [
          "Confidential Daily Tax Record",
          "Generated by Paakashala System"
        ]
      }
    };
  }
}

export const gstDocument = new GSTDocument();
export default gstDocument;
