/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as ImagePickerRouteImport } from './routes/image-picker'
import { Route as CartRouteImport } from './routes/cart'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TTableIdRouteImport } from './routes/t.$tableId'
import { Route as ItemIdRouteImport } from './routes/item.$id'

const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const ImagePickerRoute = ImagePickerRouteImport.update({
  id: '/image-picker',
  path: '/image-picker',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TTableIdRoute = TTableIdRouteImport.update({
  id: '/t/$tableId',
  path: '/t/$tableId',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemIdRoute = ItemIdRouteImport.update({
  id: '/item/$id',
  path: '/item/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/image-picker': typeof ImagePickerRoute
  '/menu': typeof MenuRoute
  '/orders': typeof OrdersRoute
  '/item/$id': typeof ItemIdRoute
  '/t/$tableId': typeof TTableIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/image-picker': typeof ImagePickerRoute
  '/menu': typeof MenuRoute
  '/orders': typeof OrdersRoute
  '/item/$id': typeof ItemIdRoute
  '/t/$tableId': typeof TTableIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/image-picker': typeof ImagePickerRoute
  '/menu': typeof MenuRoute
  '/orders': typeof OrdersRoute
  '/item/$id': typeof ItemIdRoute
  '/t/$tableId': typeof TTableIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/image-picker'
    | '/menu'
    | '/orders'
    | '/item/$id'
    | '/t/$tableId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/image-picker'
    | '/menu'
    | '/orders'
    | '/item/$id'
    | '/t/$tableId'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/image-picker'
    | '/menu'
    | '/orders'
    | '/item/$id'
    | '/t/$tableId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  ImagePickerRoute: typeof ImagePickerRoute
  MenuRoute: typeof MenuRoute
  OrdersRoute: typeof OrdersRoute
  ItemIdRoute: typeof ItemIdRoute
  TTableIdRoute: typeof TTableIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-picker': {
      id: '/image-picker'
      path: '/image-picker'
      fullPath: '/image-picker'
      preLoaderRoute: typeof ImagePickerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$tableId': {
      id: '/t/$tableId'
      path: '/t/$tableId'
      fullPath: '/t/$tableId'
      preLoaderRoute: typeof TTableIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/item/$id': {
      id: '/item/$id'
      path: '/item/$id'
      fullPath: '/item/$id'
      preLoaderRoute: typeof ItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  ImagePickerRoute: ImagePickerRoute,
  MenuRoute: MenuRoute,
  OrdersRoute: OrdersRoute,
  ItemIdRoute: ItemIdRoute,
  TTableIdRoute: TTableIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
